default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: form_list_dev

test:
  <<: *default
  database: form_list_test

production:
  <<: *default
  database: form_list_prod
